name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:15
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: yarn build
      - run: yarn link
      - run: yarn test
